// <auto-generated />
using Atividade2EFCoreClassLibrary.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using System;

namespace Atividade2EFCoreClassLibrary.Migrations
{
    [DbContext(typeof(StoreContext))]
    [Migration("lp2_CreateDatabase")]
    partial class CreateDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Atividade2EFCoreClassLibrary.Agencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BancoId");

                    b.Property<int>("Numero");

                    b.HasKey("Id");

                    b.HasIndex("BancoId");

                    b.ToTable("Agencias");
                });

            modelBuilder.Entity("Atividade2EFCoreClassLibrary.Banco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Bancos");
                });

            modelBuilder.Entity("Atividade2EFCoreClassLibrary.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ContaId");

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.HasIndex("ContaId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Atividade2EFCoreClassLibrary.ClienteSolicitacao", b =>
                {
                    b.Property<int>("ClienteId");

                    b.Property<int>("SolicitacaoId");

                    b.HasKey("ClienteId", "SolicitacaoId");

                    b.HasIndex("SolicitacaoId");

                    b.ToTable("ClienteSolicitacoes");
                });

            modelBuilder.Entity("Atividade2EFCoreClassLibrary.Conta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AgenciaId");

                    b.Property<int>("ClienteId");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("AgenciaId");

                    b.ToTable("Contas");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Conta");
                });

            modelBuilder.Entity("Atividade2EFCoreClassLibrary.Solicitacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AgenciaId");

                    b.Property<string>("Text")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("AgenciaId");

                    b.ToTable("Solicitacoes");
                });

            modelBuilder.Entity("Atividade2EFCoreClassLibrary.ContaCorrente", b =>
                {
                    b.HasBaseType("Atividade2EFCoreClassLibrary.Conta");


                    b.ToTable("ContaCorrente");

                    b.HasDiscriminator().HasValue("ContaCorrente");
                });

            modelBuilder.Entity("Atividade2EFCoreClassLibrary.ContaPoupanca", b =>
                {
                    b.HasBaseType("Atividade2EFCoreClassLibrary.Conta");

                    b.Property<decimal>("Juros");

                    b.ToTable("ContaPoupanca");

                    b.HasDiscriminator().HasValue("ContaPoupanca");
                });

            modelBuilder.Entity("Atividade2EFCoreClassLibrary.Agencia", b =>
                {
                    b.HasOne("Atividade2EFCoreClassLibrary.Banco", "Banco")
                        .WithMany()
                        .HasForeignKey("BancoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Atividade2EFCoreClassLibrary.Cliente", b =>
                {
                    b.HasOne("Atividade2EFCoreClassLibrary.Conta", "Conta")
                        .WithMany("Clientes")
                        .HasForeignKey("ContaId");
                });

            modelBuilder.Entity("Atividade2EFCoreClassLibrary.ClienteSolicitacao", b =>
                {
                    b.HasOne("Atividade2EFCoreClassLibrary.Cliente", "Cliente")
                        .WithMany("ClienteSolicitacoes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Atividade2EFCoreClassLibrary.Solicitacao", "Solicitacao")
                        .WithMany("ClienteSolicitacoes")
                        .HasForeignKey("SolicitacaoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Atividade2EFCoreClassLibrary.Conta", b =>
                {
                    b.HasOne("Atividade2EFCoreClassLibrary.Agencia", "Agencia")
                        .WithMany()
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Atividade2EFCoreClassLibrary.Solicitacao", b =>
                {
                    b.HasOne("Atividade2EFCoreClassLibrary.Agencia", "Agencia")
                        .WithMany()
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
